source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'PNObject_Example' do
    pod "PNObject", :path => "../"
    pod 'PEAR-FileManager-iOS'
    pod 'NSDate_Utils'
    pod 'UIDevice-Utils'
    pod 'AFNetworking'
end

target 'PNObject_Tests' do
    pod "PNObject", :path => "../"
    
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
end
