source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'PNObject_Example' do
    pod "PNObject", :path => "../"
    pod 'PEAR-FileManager-iOS'
    pod 'NSDate_Utils'
    pod 'UIDevice-Utils'
    pod 'AFNetworking'
    pod 'nv-ios-http-status'
    pod 'NSString-Helper'
    pod 'CodFis-Helper'
    pod 'StrongestPasswordValidator'
    pod 'AFOAuth2Manager', :git => 'https://github.com/AFNetworking/AFOAuth2Manager.git', :branch => '3_0_0_branch'

end

target 'PNObject_Tests' do
    pod "PNObject", :path => "../"
    
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
end
